[package]
name = "NightWatch"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.14.1"
sleek-ui = { git = "https://github.com/uAtomicBoolean/sleek-ui" }

[build-dependencies]
slint-build = "1.14.1"
